### ISSUE TITLE
Hey where is iOS version??

### ISSUE THREAD

**Issue by AhmedJu5002** [StarsWarrior/BlackHole#8]
Hey I just can't find the .ipa file to install blackhole in my iphone... Where I can find it?? Please someone build the project and export it in .ipa and give that file somewhere... So that I can install that in my iOS..

**Comment by LunaticPython2003** [comment]
Its available in Swaggy's Trollstore-IPA repository 

https://github.com/swaggyP36000/TrollStore-IPAs/releases/download/03-06-2024/BlackHole-1.15.11.ipa
